#!/bin/sh 

echo
echo "***********************************"
echo "********** Building fann **********"
echo "***********************************"

. ../BuildIt.env

# expand source directory
srcdir=FANN-2.2.0-Source
if [ -d $srcdir ]; then 
  rm -rf $srcdir
fi
unzip -q $srcdir.zip

# apply patches
patch -p0 -b < CMakeLists.txt.patch

cd $srcdir

# create install directories
installdir=$LIB3_DIR
for subdir in bin include lib man/man1; do
  mkdir -p $installdir/$subdir
done

# build libraries
cmake -DCMAKE_INSTALL_PREFIX=$installdir .
if [ $? -ne 0 ]; then
    echo "***** cmake failed *****"
    exit 1
fi

make
if [ $? -ne 0 ]; then
    echo "***** make failed *****"
    exit 1
fi

make install
if [ $? -ne 0 ]; then
    echo "***** make install failed *****"
    exit 1
fi

# delete expanded source directory, unless in debug mode.
cd ..
if [ "$OCSSW_DEBUG" != "1" ]; then
  rm -rf $srcdir
fi
