#!/bin/sh

echo
echo "****************************************"
echo "********** Building h4h5tools **********"
echo "****************************************"

. ../BuildIt.env

export CFLAGS="$CFLAGS -DH5_USE_16_API -I$LIB3_DIR/include"
export LDFLAGS="$LDFLAGS -L$LIB3_DIR/lib"
if [ "$OCSSW_ARCH" != "macosx_intel" ]; then
    export LIBS="-lmfhdf -ldf -lxdr -ljpeg -lz -lm"
else
    export LIBS="-lmfhdf -ldf -ljpeg -lz -lm"
fi


# expand source directory
srcdir=h4h5tools-2.2.2
if [ -d $srcdir ]; then
    rm -rf $srcdir
fi
tar xzf $srcdir.tar.gz
cd $srcdir

# create install directories
installdir=$LIB3_DIR
mkdir -p $installdir
mkdir -p $LIB3_BIN

# build libraries
./configure --prefix=$installdir --enable-static-exec --with-hdf5=$LIB3_DIR
if [ $? -ne 0 ]; then
    echo "***** configure failed *****"
    exit 1
fi

make
if [ $? -ne 0 ]; then
    echo "***** make failed *****"
    exit 1
fi

if [ "$LIB3_CHECK" = "1" ]; then
    make check
    if [ $? -ne 0 ]; then
	echo "***** make check failed *****"
	exit 1
    fi
fi

make install
if [ $? -ne 0 ]; then
    echo "***** make install failed *****"
    exit 1
fi

rsync -av $installdir/bin/ $LIB3_BIN

# delete expanded source directory, unless in debug mode.
cd ..
if [ "$OCSSW_DEBUG" != "1" ]; then
    rm -rf $srcdir
fi
