#!/bin/sh

echo
echo "*************************************"
echo "************ Building XML ***********"
echo "*************************************"

. ../BuildIt.env

# expand source directory
srcdir=libroxml-2.3.0
if [ -d $srcdir ]; then
    rm -rf $srcdir
fi
tar xzf $srcdir.tar.gz

# apply patches
#patch -b -p0 < CMakeLists.txt.patch

cd $srcdir

installdir=$LIB3_DIR
mkdir -p $installdir/lib
mkdir -p $installdir/include

# run cmake
#cmake -DCMAKE_INSTALL_PREFIX:PATH=$installdir .
./configure --prefix=$installdir
if [ $? -ne 0 ]; then
    echo "***** cmake failed *****"
    exit 1
fi

# build libraries
make -j 20
if [ $? -ne 0 ]; then
    echo "***** make failed *****"
    exit 1
fi

# install library and headers
# build libraries
make install
if [ $? -ne 0 ]; then
    echo "***** make install failed *****"
    exit 1
fi

# delete expanded source directory, unless in debug mode.
cd ..
if [ "$OCSSW_DEBUG" != "1" ]; then
   rm -rf $srcdir
fi
