#!/bin/sh

echo
echo "***********************************"
echo "********** Building GRIB **********"
echo "***********************************"

. ../BuildIt.env

if [ -d cbuild ]; then 
  rm -rf cbuild
fi
mkdir cbuild
cd cbuild

# build libraries
cmake ..
if [ $? -ne 0 ]; then
    echo "***** cmake failed *****"
    exit 1
fi

make -j 20
if [ $? -ne 0 ]; then
    echo "***** make failed *****"
    exit 1
fi

make install
if [ $? -ne 0 ]; then
    echo "***** make install failed *****"
    exit 1
fi

# delete expanded source directory, unless in debug mode.
cd ..
if [ "$OCSSW_DEBUG" != "1" ]; then
  rm -rf cbuild
fi
