/* headers for wgrib callable functions */

enum fntype {inv, output, misc, setup};

struct function {const char *name; int (*fn)(); enum fntype type; int nargs; const char *desc; int sort;};

extern struct function functions[];

extern int nfunctions;

int f_0xSec(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_bitmap(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_center(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_0_0(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_1_0(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_1_1(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_1_2(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_1_3(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_1_4(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_3_0(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_3_1(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_3_11(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_3_15(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_3_2(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_3_21(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_3_6(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_3_7(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_3_8(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_4_0(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_4_1(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_4_10(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_4_2(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_4_3(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_4_4(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_4_5a(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_4_5b(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_4_6(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_4_7(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_4_9(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_5_0(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_5_1(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_5_5(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_6_0(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_ctl_inv(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_code_table_0_0(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_ens(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_flag_table_3_10(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_flag_table_3_3(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_flag_table_3_4(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_flag_table_3_5(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_flag_table_3_9(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_ftime(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_grid(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_ij(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1, char *arg2);
int f_ijlat(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1, char *arg2);
int f_ilat(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_lev(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_lev0(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_lola(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1, char *arg2, char *arg3, char *arg4);
int f_lon(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1, char *arg2);
int f_max(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_min(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_MM(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_N_ens(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_nl(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_nlons(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_npts(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_nxny(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_packing(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_pds_fcst_time(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_print(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_code_table_4_3(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_processid(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_range(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_RT(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_s(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_scan(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_Sec0(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_Sec3(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_Sec4(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_Sec5(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_Sec6(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_Sec_len(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_stats(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_subcenter(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_t(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_T(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_table(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_var(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_varX(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_verf(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_vt(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_VT(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_YY(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_colon(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_end(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_grib_bits(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_h(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_header(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_help(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_if(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_ijundefine(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1, char *arg2, char *arg3);
int f_no_header(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_one_line(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_end(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_submsg(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_text_col(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_text_fmt(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_undefine(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1, char *arg2, char *arg3);
int f_undefine_val(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_v(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_v0(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_v(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_v2(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_version(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_bin(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_grib(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_GRIB(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_grib_out(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_ieee(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_netcdf(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_spread(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_text(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_append(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_d(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_flush(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_i(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_match(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_nc_grads(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_nc_nlev(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_nc_pack(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_nc_table(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_no_append(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_no_flush(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_no_nc_grads(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_no_nc_pack(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_no_nc_table(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
int f_not(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_order(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local, char *arg1);
int f_tigge(int mode, unsigned char **sec, float *data, unsigned int ndata, char *inv, void **local);
