#!/bin/sh

echo
echo "**********************************"
echo "********** Building gsl **********"
echo "**********************************"

. ../BuildIt.env

# expand source directory
srcdir=gsl-1.16
if [ -d $srcdir ]; then
   rm -rf $srcdir
fi
tar xzf $srcdir.tar.gz
cd $srcdir

# create install directories
installdir=$LIB3_DIR
mkdir -p $installdir
mkdir -p $LIB3_BIN

if [ $OCSSW_ARCH = "macosx_intel" ]; then
    export CFLAGS="$CFLAGS -O1"
fi

# build libraries
./configure --prefix=$installdir --disable-shared
if [ $? -ne 0 ]; then
    echo "***** configure failed *****"
    exit 1
fi

make
if [ $? -ne 0 ]; then
    echo "***** make failed *****"
    exit 1
fi

if [ "$LIB3_CHECK" = "1" ]; then
    make check
    if [ $? -ne 0 ]; then
	echo "***** make check failed *****"
	exit 1
    fi
fi
make install
if [ $? -ne 0 ]; then
    echo "***** make install failed *****"
    exit 1
fi

# copy bin dir to common lib3 bin dir
rsync -av $installdir/bin/ $LIB3_BIN

# delete expanded source directory, unless in debug mode.
cd ..
if [ "$OCSSW_DEBUG" != "1" ]; then
    rm -rf $srcdir
fi
