# ===========================================================================
#       Begin Program Specific Block
# ===========================================================================

# Library to make
LIBRARY = libg2.a

# Source files for LIBRARY
OBJ     = \
	g2grids.o \
	params_ecmwf.o \
	gribmod.o \
	realloc.o \
	gridtemplates.o \
	pdstemplates.o \
	drstemplates.o \
	params.o \
	addfield.o \
	addgrid.o \
	addlocal.o \
	cmplxpack.o \
	compack.o \
	comunpack.o \
	gb_info.o \
	gbytesc.o \
	gdt2gds.o \
	getdim.o \
	getfield.o \
	getg2i.o \
	getg2ir.o \
	getgb2l.o \
	getgb2.o \
	getgb2p.o \
	getgb2r.o \
	getgb2rp.o \
	getgb2s.o \
	getidx.o \
	getlocal.o \
	getpoly.o \
	gettemplates.o \
	gf_free.o \
	gf_getfld.o \
	gf_unpack1.o \
	gf_unpack2.o \
	gf_unpack3.o \
	gf_unpack4.o \
	gf_unpack5.o \
	gf_unpack6.o \
	gf_unpack7.o \
	gribcreate.o \
	gribend.o \
	gribinfo.o \
	ixgb2.o \
	jpcpack.o \
	jpcunpack.o \
	misspack.o \
	mkieee.o \
	pack_gp.o \
	pngpack.o \
	pngunpack.o \
	putgb2.o \
	rdieee.o \
	reduce.o \
	simpack.o \
	simunpack.o \
	skgb.o \
	specpack.o \
	specunpack.o

include $(MAKEFILE_LIB_TEMPLATE)

