# ===========================================================================
#	Begin Program Specific Block
# ===========================================================================

MAKEFILE = Makefile

# Progam to make
EXE	= wgrib

# Object modules for EXE
OBJ	= wgrib.o

# Include file locations
INCLUDE	= 

# Library locations
LIBS 	= 

# Libraries required to link
LLIBS 	= 

include $(MAKEFILE_APP_TEMPLATE)
