#!/bin/sh

echo
echo "***********************************"
echo "********** Building jpeg **********"
echo "***********************************"

. ../BuildIt.env

# expand source directory
srcdir=jpeg-6b
if [ -d $srcdir ]; then
    rm -rf $srcdir
fi
tar xzf jpegsrc.v6b.tar.gz
cd $srcdir

# create install directories
installdir=$LIB3_DIR
for subdir in bin include lib man/man1; do
  mkdir -p $installdir/$subdir
done

# build libraries
./configure --prefix=$installdir
if [ $? -ne 0 ]; then
    echo "***** configure failed *****"
    exit 1
fi

make
if [ $? -ne 0 ]; then
    echo "***** make failed *****"
    exit 1
fi

if [ "$LIB3_CHECK" = "1" ]; then
    make check
    if [ $? -ne 0 ]; then
	echo "***** make check failed *****"
	exit 1
    fi
fi

make install
if [ $? -ne 0 ]; then
    echo "***** make install failed *****"
    exit 1
fi

make install-lib
if [ $? -ne 0 ]; then
    echo "***** make install-lib failed *****"
    exit 1
fi

# copy bin dir to common lib3 bin dir
rsync -av $installdir/bin/ $LIB3_BIN

# delete expanded source directory, unless in debug mode.
cd ..
if [ "$OCSSW_DEBUG" != "1" ]; then
    rm -rf $srcdir
fi
