#!/bin/sh

echo
echo "*************************************"
echo "********* Building lapack ***********"
echo "*************************************"

. ../BuildIt.env


#----------------------
# temporary fix for mac
#----------------------
if [  "$OCSSW_ARCH" = "macosx_intel"  ]; then
    export LIB3_CHECK=0
fi

# expand source directory
srcdir=lapack-3.4.2
if [ -d $srcdir ]; then
    rm -rf $srcdir
fi
tar xzf $srcdir.tgz

cd $srcdir

installdir=$LIB3_DIR
mkdir -p $installdir/lib
mkdir -p $installdir/include

# build libraries
cmake -DCMAKE_INSTALL_PREFIX:PATH=$installdir .
if [ $? -ne 0 ]; then
    echo "***** make failed *****"
    exit 1
fi

make -j 20
if [ $? -ne 0 ]; then
    echo "***** make failed *****"
    exit 1
fi

# test
if [  "$LIB3_CHECK" = "1"  ]; then
    echo "---- running tests ----"
    make test
    if [ $? -ne 0 ]; then
	echo "***** make test failed *****"
	exit 1
    fi
fi

# install library and headers
make install
if [ $? -ne 0 ]; then
    echo "***** make install failed *****"
    exit 1
fi

# delete expanded source directory, unless in debug mode.
cd ..
if [ "$OCSSW_DEBUG" != "1" ]; then
   rm -rf $srcdir
fi
